### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by rayt168** [aureliojargas/sedsed#17]
Hello, I am running Cygwin.  I see that sedsed requires Python.  I have downloaded Python and installed it as well.  I downloaded the sedsedzip file and tried to execute sedsed.  It did NOT work.  Please be advised that I am only a Unix newbie.  Is that the correct procedure?  Any input or assistance would be deeply appreciated.  Thank you.

Ray T

**Comment by aureliojargas** [comment]
Hi @rayt168,

I'm sorry not addressing this before. After all this years, you probably moved on or already fixed it. So I'm closing this ticket. Please reopen it if necessary.
