### ISSUE TITLE
Doesn't recognize '~' or '+' and validation error in Python script under Win7 Pro sp1 x86

### ISSUE THREAD

**Issue by w2kpro** [aureliojargas/sedsed#21]
Sedsed v 1.1-dev, GNU sed 4.2.1, Python 3.6 32-bit Windows 7 Pro x86 sp1

script.sed = `1~2h; 2~2{H; g; s/\n/ /; p}`
input.txt = 
1 One
2 Two
3 Three
4 Four

    $ sedsed -n -d -f script.sed input.txt
    ERROR: invalid SED command '~' at line 2

    $ sed -n -f script4.sed input1.txt
    1 One 2 Two
    3 Three 4 Four

Also, `/1 One/,+2!d`
 
    ERROR: invalid SED command '+' at line 2

    $ sed "/1 One/,+2!d"
    1 One
    2 Two
    3 Three

There is also a problem with line 331 of the Python script:
 
    if action == 'debug':
        validate_script_syntax(sedscript)

I have had to REM these two lines as the following error occurs:

sed: couldn't open file 'C:\Users\ADMINI~1\AppData\Local\Temp\tmpza2li4vs': Invalid argument
ERROR: #0: syntax error on your SED script, please fix it before.

**Comment by aureliojargas** [comment]
Hi @w2kpro ,

Thanks for the report!

In the current version of `sedsed` in this repository (still not officially released), there is a new parser (#52) and both `~` and `+` GNU sed address extensions are now recognized:

```console
$ ./sedsed.py -e "1~2h; 2~2{H; g; s/\n/ /; p}"
1~2 h
2~2 {
    H
    g
    s/\n/ /
    p
}
$ ./sedsed.py -e '/1 One/,+2!d' 
/1 One/,+2 !d
$
```
