### ISSUE TITLE
[RFE] add a new command line option to specify the sed executable (e.g. --sedbin /usr/local/bin/gsed)

### ISSUE THREAD

**Issue by clarkwang** [aureliojargas/sedsed#72]
This will make it easier to test different sed on one single system (for example I installed GNU sed on my macOS).

**Comment by aureliojargas** [comment]
Fixed, thanks!

Also, the new `--sedbin` option is now used to run sedsed in the test suite. See 303352005ba7db6bdf64113deafa40f55b2050b2
