### ISSUE TITLE
sedsed as a Python module

### ISSUE THREAD

**Issue by aureliojargas** [aureliojargas/sedsed#9]
Besides being run from the command line,  sedsed should also be importable as a Python module.

This will enable unit tests on classes/methods and the emulator could be used inside Python programs.

**Comment by jayvdb** [comment]
I believe this has been done, and released on PyPI as 1.1dev0

It would be good to have a final 1.1 release, with tests included in the sdist.

**Comment by aureliojargas** [comment]
Hi @jayvdb, unfortunately, this work is still pending.

Currently sedsed works only from the command line. If you try to import it, an error is shown since it will try to execute and parse something:

```python
>>> import sedsed
ERROR: there's no SED script to parse! (try --help)
```

**Comment by aureliojargas** [comment]
@jayvdb You're right about a new version release, I'll try to get it done, https://github.com/aureliojargas/sedsed/issues/23 was opened for that. Thanks for the feedback!

**Comment by aureliojargas** [comment]
Done
